name: Veterinaria Happy Friends

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Frontend (Vite)
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Check Vite build output
        run: |
          if [ ! -f frontend/dist/index.html ]; then
            echo "ERROR: El build de Vite no generó index.html en frontend/dist."
            exit 1
          fi
          # Si no existe la carpeta assets, crearla vacía para evitar error FTP
          if [ ! -d frontend/dist/assets ]; then
            echo "La carpeta assets no existe, se creará vacía."
            mkdir -p frontend/dist/assets
          fi
          echo "Build de Vite generado correctamente."

      - name: Prepare deploy-dist folder
        run: |
          rm -rf deploy-dist
          mkdir -p deploy-dist/backend/public
          # Copiar backend necesario
          rsync -av --exclude='node_modules' --exclude='tests' --exclude='.env.example' --exclude='README.md' backend/ deploy-dist/backend/
          # Copiar build del frontend (incluyendo index.html y assets) a la carpeta pública del backend
          rsync -av frontend/dist/ deploy-dist/backend/public/

      - name: Deploy to Production (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /deploy/236_Proyecto_main/
          local-dir: ./deploy-dist/backend/
          exclude: |
            **/.git*
            **/node_modules/**
            **/tests/**
            **/docker-compose.yml
            **/Dockerfile*
            **/.env.example
            **/README.md
            **/.github/**